sudo: false

language: c

addons:
  postgresql: "9.3"
  apt:
   packages:
   - libgmp-dev

before_install:
  # stack
  - mkdir -p ~/.local/bin
  - export PATH=$HOME/.local/bin:$PATH
  - travis_retry curl -L https://www.stackage.org/stack/linux-x86_64 | tar xz --wildcards --strip-components=1 -C ~/.local/bin '*/stack'

script:
  - stack init
  - stack build --test --no-run-tests --install-ghc

cache:
  directories:
    - $HOME/.stack
