sudo: false

language: c

addons:
  apt:
   packages:
   - libgmp-dev

services:
  - mysql

matrix:
  include:
  - env: ARGS="--resolver lts"
    compiler: ": #newest LTS"
  - env: ARGS="--resolver nightly"
    compiler: ": #newest nightly"
  - env: ARGS="--resolver lts-6"
    compiler: ": #newest lts 6"

before_install:
  # Using compiler above sets CC to an invalid value, so unset it
  - unset CC

  # stack
  - mkdir -p ~/.local/bin
  - export PATH=$HOME/.local/bin:$PATH
  - travis_retry curl -L https://www.stackage.org/stack/linux-x86_64 | tar xz --wildcards --strip-components=1 -C ~/.local/bin '*/stack'

before_script:
  - |
    mysql <<EOF
    CREATE DATABASE PROJECTNAME_test;
    GRANT USAGE ON *.* TO PROJECTNAME@localhost IDENTIFIED BY 'PROJECTNAME';
    GRANT ALL PRIVILEGES ON PROJECTNAME_test.* TO PROJECTNAME@localhost;
    EOF

script:
  - stack init $ARGS
  - stack build --test --install-ghc

cache:
  directories:
    - $HOME/.stack
